using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Weather
{

	public static class WeatherIconFont
	{
		// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
		// If you change the class to 'public' in order to use it outside its assembly
		//  you should also change the fields from 'static readonly' to 'public static readonly'

		#region 字典




		private static Dictionary<string, string> dic = new Dictionary<string, string>()
	{
				{"100","\uf101"},
		{"101","\uf102"},
		{"102","\uf103"},
		{"103","\uf104"},
		{"104","\uf105"},
		{"150","\uf106"},
		{"151","\uf107"},
		{"152","\uf108"},
		{"153","\uf109"},
		{"300","\uf10a"},
		{"301","\uf10b"},
		{"302","\uf10c"},
		{"303","\uf10d"},
		{"304","\uf10e"},
		{"305","\uf10f"},
		{"306","\uf110"},
		{"307","\uf111"},
		{"308","\uf112"},
		{"309","\uf113"},
		{"310","\uf114"},
		{"311","\uf115"},
		{"312","\uf116"},
		{"313","\uf117"},
		{"314","\uf118"},
		{"315","\uf119"},
		{"316","\uf11a"},
		{"317","\uf11b"},
		{"318","\uf11c"},
		{"350","\uf11d"},
		{"351","\uf11e"},
		{"399","\uf11f"},
		{"400","\uf120"},
		{"401","\uf121"},
		{"402","\uf122"},
		{"403","\uf123"},
		{"404","\uf124"},
		{"405","\uf125"},
		{"406","\uf126"},
		{"407","\uf127"},
		{"408","\uf128"},
		{"409","\uf129"},
		{"410","\uf12a"},
		{"456","\uf12b"},
		{"457","\uf12c"},
		{"499","\uf12d"},
		{"500","\uf12e"},
		{"501","\uf12f"},
		{"502","\uf130"},
		{"503","\uf131"},
		{"504","\uf132"},
		{"507","\uf133"},
		{"508","\uf134"},
		{"509","\uf135"},
		{"510","\uf136"},
		{"511","\uf137"},
		{"512","\uf138"},
		{"513","\uf139"},
		{"514","\uf13a"},
		{"515","\uf13b"},
		{"800","\uf13c"},
		{"801","\uf13d"},
		{"802","\uf13e"},
		{"803","\uf13f"},
		{"804","\uf140"},
		{"805","\uf141"},
		{"806","\uf142"},
		{"807","\uf143"},
		{"900","\uf144"},
		{"901","\uf145"},
		{"999","\uf146"},
		{"1001","\uf147"},
		{"1002","\uf148"},
		{"1003","\uf149"},
		{"1004","\uf14a"},
		{"1005","\uf14b"},
		{"1006","\uf14c"},
		{"1007","\uf14d"},
		{"1008","\uf14e"},
		{"1009","\uf14f"},
		{"1010","\uf150"},
		{"1011","\uf151"},
		{"1012","\uf152"},
		{"1013","\uf153"},
		{"1014","\uf154"},
		{"1015","\uf155"},
		{"1016","\uf156"},
		{"1017","\uf157"},
		{"1018","\uf158"},
		{"1019","\uf159"},
		{"1020","\uf15a"},
		{"1021","\uf15b"},
		{"1022","\uf15c"},
		{"1023","\uf15d"},
		{"1024","\uf15e"},
		{"1025","\uf15f"},
		{"1026","\uf160"},
		{"1027","\uf161"},
		{"1028","\uf162"},
		{"1029","\uf163"},
		{"1030","\uf164"},
		{"1031","\uf165"},
		{"1032","\uf166"},
		{"1033","\uf167"},
		{"1034","\uf168"},
		{"1035","\uf169"},
		{"1036","\uf16a"},
		{"1037","\uf16b"},
		{"1038","\uf16c"},
		{"1039","\uf16d"},
		{"1040","\uf16e"},
		{"1041","\uf16f"},
		{"1042","\uf170"},
		{"1043","\uf171"},
		{"1044","\uf172"},
		{"1045","\uf173"},
		{"1046","\uf174"},
		{"1047","\uf175"},
		{"1048","\uf176"},
		{"1049","\uf177"},
		{"1050","\uf178"},
		{"1051","\uf179"},
		{"1052","\uf17a"},
		{"1053","\uf17b"},
		{"1054","\uf17c"},
		{"1055","\uf17d"},
		{"1056","\uf17e"},
		{"1057","\uf17f"},
		{"1058","\uf180"},
		{"1059","\uf181"},
		{"1061","\uf182"},
		{"1064","\uf183"},
		{"1101","\uf184"},
		{"1302","\uf185"},
		{"1402","\uf186"},
		{"1601","\uf187"},
		{"1602","\uf188"},
		{"1603","\uf189"},
		{"1604","\uf18a"},
		{"1605","\uf18b"},
		{"1606","\uf18c"},
		{"2002","\uf18f"},
		{"2004","\uf191"},
		{"2006","\uf193"},
		{"2008","\uf195"},
		{"2009","\uf196"},
		{"2010","\uf197"},
		{"2011","\uf198"},
		{"2015","\uf19c"},
		{"2016","\uf19d"},
		{"2017","\uf19e"},
		{"2018","\uf19f"},
		{"2019","\uf1a0"},
		{"2020","\uf1a1"},
		{"2021","\uf1a2"},
		{"2022","\uf1a3"},
		{"2023","\uf1a4"},
		{"2024","\uf1a5"},
		{"2025","\uf1a6"},
		{"2026","\uf1a7"},
		{"2027","\uf1a8"},
		{"2028","\uf1a9"},
		{"9998","\uf1aa"},
		{"100Fill","\uf1ac"},
		{"101Fill","\uf1ad"},
		{"102Fill","\uf1ae"},
		{"103Fill","\uf1af"},
		{"104Fill","\uf1b0"},
		{"150Fill","\uf1b1"},
		{"151Fill","\uf1b2"},
		{"152Fill","\uf1b3"},
		{"153Fill","\uf1b4"},
		{"300Fill","\uf1b5"},
		{"301Fill","\uf1b6"},
		{"302Fill","\uf1b7"},
		{"303Fill","\uf1b8"},
		{"304Fill","\uf1b9"},
		{"305Fill","\uf1ba"},
		{"306Fill","\uf1bb"},
		{"307Fill","\uf1bc"},
		{"308Fill","\uf1bd"},
		{"309Fill","\uf1be"},
		{"310Fill","\uf1bf"},
		{"311Fill","\uf1c0"},
		{"312Fill","\uf1c1"},
		{"313Fill","\uf1c2"},
		{"314Fill","\uf1c3"},
		{"315Fill","\uf1c4"},
		{"316Fill","\uf1c5"},
		{"317Fill","\uf1c6"},
		{"318Fill","\uf1c7"},
		{"350Fill","\uf1c8"},
		{"351Fill","\uf1c9"},
		{"399Fill","\uf1ca"},
		{"400Fill","\uf1cb"},
		{"401Fill","\uf1cc"},
		{"402Fill","\uf1cd"},
		{"403Fill","\uf1ce"},
		{"404Fill","\uf1cf"},
		{"405Fill","\uf1d0"},
		{"406Fill","\uf1d1"},
		{"407Fill","\uf1d2"},
		{"408Fill","\uf1d3"},
		{"409Fill","\uf1d4"},
		{"410Fill","\uf1d5"},
		{"456Fill","\uf1d6"},
		{"457Fill","\uf1d7"},
		{"499Fill","\uf1d8"},
		{"500Fill","\uf1d9"},
		{"501Fill","\uf1da"},
		{"502Fill","\uf1db"},
		{"503Fill","\uf1dc"},
		{"504Fill","\uf1dd"},
		{"507Fill","\uf1de"},
		{"508Fill","\uf1df"},
		{"509Fill","\uf1e0"},
		{"510Fill","\uf1e1"},
		{"511Fill","\uf1e2"},
		{"512Fill","\uf1e3"},
		{"513Fill","\uf1e4"},
		{"514Fill","\uf1e5"},
		{"515Fill","\uf1e6"},
		{"900Fill","\uf1e7"},
		{"901Fill","\uf1e8"},
		{"999Fill","\uf1e9"}
	};
		#endregion

		/// <summary>
		/// 根据可以获得value
		/// </summary>
		/// <param name="key"></param>
		/// <returns></returns>
		public static string GetValueByKey(string key)
		{
			string v = "";
			if (dic.TryGetValue(key, out v))
			{
				return v;
			}

			return "";
		}


		public static readonly string _100 = "\uf101";
		public static readonly string _101 = "\uf102";
		public static readonly string _102 = "\uf103";
		public static readonly string _103 = "\uf104";
		public static readonly string _104 = "\uf105";
		public static readonly string _150 = "\uf106";
		public static readonly string _151 = "\uf107";
		public static readonly string _152 = "\uf108";
		public static readonly string _153 = "\uf109";
		public static readonly string _300 = "\uf10a";
		public static readonly string _301 = "\uf10b";
		public static readonly string _302 = "\uf10c";
		public static readonly string _303 = "\uf10d";
		public static readonly string _304 = "\uf10e";
		public static readonly string _305 = "\uf10f";
		public static readonly string _306 = "\uf110";
		public static readonly string _307 = "\uf111";
		public static readonly string _308 = "\uf112";
		public static readonly string _309 = "\uf113";
		public static readonly string _310 = "\uf114";
		public static readonly string _311 = "\uf115";
		public static readonly string _312 = "\uf116";
		public static readonly string _313 = "\uf117";
		public static readonly string _314 = "\uf118";
		public static readonly string _315 = "\uf119";
		public static readonly string _316 = "\uf11a";
		public static readonly string _317 = "\uf11b";
		public static readonly string _318 = "\uf11c";
		public static readonly string _350 = "\uf11d";
		public static readonly string _351 = "\uf11e";
		public static readonly string _399 = "\uf11f";
		public static readonly string _400 = "\uf120";
		public static readonly string _401 = "\uf121";
		public static readonly string _402 = "\uf122";
		public static readonly string _403 = "\uf123";
		public static readonly string _404 = "\uf124";
		public static readonly string _405 = "\uf125";
		public static readonly string _406 = "\uf126";
		public static readonly string _407 = "\uf127";
		public static readonly string _408 = "\uf128";
		public static readonly string _409 = "\uf129";
		public static readonly string _410 = "\uf12a";
		public static readonly string _456 = "\uf12b";
		public static readonly string _457 = "\uf12c";
		public static readonly string _499 = "\uf12d";
		public static readonly string _500 = "\uf12e";
		public static readonly string _501 = "\uf12f";
		public static readonly string _502 = "\uf130";
		public static readonly string _503 = "\uf131";
		public static readonly string _504 = "\uf132";
		public static readonly string _507 = "\uf133";
		public static readonly string _508 = "\uf134";
		public static readonly string _509 = "\uf135";
		public static readonly string _510 = "\uf136";
		public static readonly string _511 = "\uf137";
		public static readonly string _512 = "\uf138";
		public static readonly string _513 = "\uf139";
		public static readonly string _514 = "\uf13a";
		public static readonly string _515 = "\uf13b";
		public static readonly string _800 = "\uf13c";
		public static readonly string _801 = "\uf13d";
		public static readonly string _802 = "\uf13e";
		public static readonly string _803 = "\uf13f";
		public static readonly string _804 = "\uf140";
		public static readonly string _805 = "\uf141";
		public static readonly string _806 = "\uf142";
		public static readonly string _807 = "\uf143";
		public static readonly string _900 = "\uf144";
		public static readonly string _901 = "\uf145";
		public static readonly string _999 = "\uf146";
		public static readonly string _1001 = "\uf147";
		public static readonly string _1002 = "\uf148";
		public static readonly string _1003 = "\uf149";
		public static readonly string _1004 = "\uf14a";
		public static readonly string _1005 = "\uf14b";
		public static readonly string _1006 = "\uf14c";
		public static readonly string _1007 = "\uf14d";
		public static readonly string _1008 = "\uf14e";
		public static readonly string _1009 = "\uf14f";
		public static readonly string _1010 = "\uf150";
		public static readonly string _1011 = "\uf151";
		public static readonly string _1012 = "\uf152";
		public static readonly string _1013 = "\uf153";
		public static readonly string _1014 = "\uf154";
		public static readonly string _1015 = "\uf155";
		public static readonly string _1016 = "\uf156";
		public static readonly string _1017 = "\uf157";
		public static readonly string _1018 = "\uf158";
		public static readonly string _1019 = "\uf159";
		public static readonly string _1020 = "\uf15a";
		public static readonly string _1021 = "\uf15b";
		public static readonly string _1022 = "\uf15c";
		public static readonly string _1023 = "\uf15d";
		public static readonly string _1024 = "\uf15e";
		public static readonly string _1025 = "\uf15f";
		public static readonly string _1026 = "\uf160";
		public static readonly string _1027 = "\uf161";
		public static readonly string _1028 = "\uf162";
		public static readonly string _1029 = "\uf163";
		public static readonly string _1030 = "\uf164";
		public static readonly string _1031 = "\uf165";
		public static readonly string _1032 = "\uf166";
		public static readonly string _1033 = "\uf167";
		public static readonly string _1034 = "\uf168";
		public static readonly string _1035 = "\uf169";
		public static readonly string _1036 = "\uf16a";
		public static readonly string _1037 = "\uf16b";
		public static readonly string _1038 = "\uf16c";
		public static readonly string _1039 = "\uf16d";
		public static readonly string _1040 = "\uf16e";
		public static readonly string _1041 = "\uf16f";
		public static readonly string _1042 = "\uf170";
		public static readonly string _1043 = "\uf171";
		public static readonly string _1044 = "\uf172";
		public static readonly string _1045 = "\uf173";
		public static readonly string _1046 = "\uf174";
		public static readonly string _1047 = "\uf175";
		public static readonly string _1048 = "\uf176";
		public static readonly string _1049 = "\uf177";
		public static readonly string _1050 = "\uf178";
		public static readonly string _1051 = "\uf179";
		public static readonly string _1052 = "\uf17a";
		public static readonly string _1053 = "\uf17b";
		public static readonly string _1054 = "\uf17c";
		public static readonly string _1055 = "\uf17d";
		public static readonly string _1056 = "\uf17e";
		public static readonly string _1057 = "\uf17f";
		public static readonly string _1058 = "\uf180";
		public static readonly string _1059 = "\uf181";
		public static readonly string _1061 = "\uf182";
		public static readonly string _1064 = "\uf183";
		public static readonly string _1101 = "\uf184";
		public static readonly string _1302 = "\uf185";
		public static readonly string _1402 = "\uf186";
		public static readonly string _1601 = "\uf187";
		public static readonly string _1602 = "\uf188";
		public static readonly string _1603 = "\uf189";
		public static readonly string _1604 = "\uf18a";
		public static readonly string _1605 = "\uf18b";
		public static readonly string _1606 = "\uf18c";
		public static readonly string _2002 = "\uf18f";
		public static readonly string _2004 = "\uf191";
		public static readonly string _2006 = "\uf193";
		public static readonly string _2008 = "\uf195";
		public static readonly string _2009 = "\uf196";
		public static readonly string _2010 = "\uf197";
		public static readonly string _2011 = "\uf198";
		public static readonly string _2015 = "\uf19c";
		public static readonly string _2016 = "\uf19d";
		public static readonly string _2017 = "\uf19e";
		public static readonly string _2018 = "\uf19f";
		public static readonly string _2019 = "\uf1a0";
		public static readonly string _2020 = "\uf1a1";
		public static readonly string _2021 = "\uf1a2";
		public static readonly string _2022 = "\uf1a3";
		public static readonly string _2023 = "\uf1a4";
		public static readonly string _2024 = "\uf1a5";
		public static readonly string _2025 = "\uf1a6";
		public static readonly string _2026 = "\uf1a7";
		public static readonly string _2027 = "\uf1a8";
		public static readonly string _2028 = "\uf1a9";
		public static readonly string _9998 = "\uf1aa";
		public static readonly string _100Fill = "\uf1ac";
		public static readonly string _101Fill = "\uf1ad";
		public static readonly string _102Fill = "\uf1ae";
		public static readonly string _103Fill = "\uf1af";
		public static readonly string _104Fill = "\uf1b0";
		public static readonly string _150Fill = "\uf1b1";
		public static readonly string _151Fill = "\uf1b2";
		public static readonly string _152Fill = "\uf1b3";
		public static readonly string _153Fill = "\uf1b4";
		public static readonly string _300Fill = "\uf1b5";
		public static readonly string _301Fill = "\uf1b6";
		public static readonly string _302Fill = "\uf1b7";
		public static readonly string _303Fill = "\uf1b8";
		public static readonly string _304Fill = "\uf1b9";
		public static readonly string _305Fill = "\uf1ba";
		public static readonly string _306Fill = "\uf1bb";
		public static readonly string _307Fill = "\uf1bc";
		public static readonly string _308Fill = "\uf1bd";
		public static readonly string _309Fill = "\uf1be";
		public static readonly string _310Fill = "\uf1bf";
		public static readonly string _311Fill = "\uf1c0";
		public static readonly string _312Fill = "\uf1c1";
		public static readonly string _313Fill = "\uf1c2";
		public static readonly string _314Fill = "\uf1c3";
		public static readonly string _315Fill = "\uf1c4";
		public static readonly string _316Fill = "\uf1c5";
		public static readonly string _317Fill = "\uf1c6";
		public static readonly string _318Fill = "\uf1c7";
		public static readonly string _350Fill = "\uf1c8";
		public static readonly string _351Fill = "\uf1c9";
		public static readonly string _399Fill = "\uf1ca";
		public static readonly string _400Fill = "\uf1cb";
		public static readonly string _401Fill = "\uf1cc";
		public static readonly string _402Fill = "\uf1cd";
		public static readonly string _403Fill = "\uf1ce";
		public static readonly string _404Fill = "\uf1cf";
		public static readonly string _405Fill = "\uf1d0";
		public static readonly string _406Fill = "\uf1d1";
		public static readonly string _407Fill = "\uf1d2";
		public static readonly string _408Fill = "\uf1d3";
		public static readonly string _409Fill = "\uf1d4";
		public static readonly string _410Fill = "\uf1d5";
		public static readonly string _456Fill = "\uf1d6";
		public static readonly string _457Fill = "\uf1d7";
		public static readonly string _499Fill = "\uf1d8";
		public static readonly string _500Fill = "\uf1d9";
		public static readonly string _501Fill = "\uf1da";
		public static readonly string _502Fill = "\uf1db";
		public static readonly string _503Fill = "\uf1dc";
		public static readonly string _504Fill = "\uf1dd";
		public static readonly string _507Fill = "\uf1de";
		public static readonly string _508Fill = "\uf1df";
		public static readonly string _509Fill = "\uf1e0";
		public static readonly string _510Fill = "\uf1e1";
		public static readonly string _511Fill = "\uf1e2";
		public static readonly string _512Fill = "\uf1e3";
		public static readonly string _513Fill = "\uf1e4";
		public static readonly string _514Fill = "\uf1e5";
		public static readonly string _515Fill = "\uf1e6";
		public static readonly string _900Fill = "\uf1e7";
		public static readonly string _901Fill = "\uf1e8";
		public static readonly string _999Fill = "\uf1e9";

	}
}